/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe — returns ok when the API is up. */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all provinces (lean payload for the il-hub + map). */
        get: operations["ProvinceController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces/map-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulk hover-card summary for all provinces (homepage SVG map, build-time embed). */
        get: operations["ProvinceController_findMapSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one province by its TR or EN slug (full detail). */
        get: operations["ProvinceController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @description Liveness status of the API. Always "ok" when the service responds.
             * @example ok
             */
            status: string;
        };
        ProvinceListItemDto: {
            /**
             * @description Plaka kodu (stable, unique).
             * @example 34
             */
            plateCode: string;
            /**
             * @description İl adı (TR).
             * @example İstanbul
             */
            nameTr: string;
            /**
             * @description Coğrafi bölge.
             * @enum {string}
             */
            region: "MARMARA" | "EGE" | "AKDENIZ" | "IC_ANADOLU" | "KARADENIZ" | "DOGU_ANADOLU" | "GUNEYDOGU_ANADOLU";
            /**
             * @description TR slug (routing key).
             * @example istanbul
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example istanbul
             */
            slugEn: string;
        };
        ProvinceMapSummaryDto: {
            /**
             * @description Plaka kodu (stable, unique).
             * @example 34
             */
            plateCode: string;
            /**
             * @description İl adı (TR).
             * @example İstanbul
             */
            nameTr: string;
            /**
             * @description Coğrafi bölge.
             * @enum {string}
             */
            region: "MARMARA" | "EGE" | "AKDENIZ" | "IC_ANADOLU" | "KARADENIZ" | "DOGU_ANADOLU" | "GUNEYDOGU_ANADOLU";
            /**
             * @description TR slug (routing key — kart tıklaması).
             * @example istanbul
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example istanbul
             */
            slugEn: string;
            /**
             * @description Nüfus (TÜİK ADNKS). Null until fact-checked.
             * @example 15754053
             */
            population: number | null;
            /**
             * @description Nüfus referans yılı.
             * @example 2025
             */
            populationYear: number | null;
            /**
             * @description Yüzölçümü (km², HGM).
             * @example 5461
             */
            areaKm2: number | null;
            /**
             * @description İlçe sayısı.
             * @example 39
             */
            districtCount: number | null;
        };
        HydrographyFeatureDto: {
            /**
             * @description Öz ad.
             * @example Ömerli Barajı
             */
            name: string;
            /**
             * @description Özellik türü (baraj/nehir/göl) — ASCII değer; TR etiketi web tarafında.
             * @example baraj
             * @enum {string}
             */
            type: "baraj" | "nehir" | "gol";
        };
        EconomyIndicatorDto: {
            /**
             * @description İstatistiğin ölçtüğü büyüklük.
             * @example GSYH'de Türkiye payı
             */
            label: string;
            /**
             * @description Değer, string — pay/sıra/ürün adı olabildiği için (heterojen).
             * @example %30,2
             */
            value: string;
            /**
             * @description İstatistiğin referans yılı.
             * @example 2024
             */
            year: number;
            /**
             * @description Otoriter kaynak.
             * @example TÜİK Bölgesel GSYH
             */
            source: string;
        };
        ProvinceDetailDto: {
            /**
             * @description Plaka kodu.
             * @example 34
             */
            plateCode: string;
            /**
             * @description İl adı (TR).
             * @example İstanbul
             */
            nameTr: string;
            /**
             * @description TR slug (routing key).
             * @example istanbul
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example istanbul
             */
            slugEn: string;
            /**
             * @description Coğrafi bölge.
             * @enum {string}
             */
            region: "MARMARA" | "EGE" | "AKDENIZ" | "IC_ANADOLU" | "KARADENIZ" | "DOGU_ANADOLU" | "GUNEYDOGU_ANADOLU";
            /**
             * @description Yazılı açılış cümlesi (il girişi). Null ise web veri-tabanlı bir cümle kurar (fallback).
             * @example İstanbul, Karadeniz ile Marmara Denizi'ni birbirine bağlayan Boğaz'ın iki yakasına kurulmuştur.
             */
            introTr: string | null;
            /**
             * @description Nüfus (TÜİK ADNKS). Null until fact-checked.
             * @example 15754053
             */
            population: number | null;
            /**
             * @description Nüfus referans yılı.
             * @example 2025
             */
            populationYear: number | null;
            /**
             * @description Yüzölçümü (km², HGM).
             * @example 5461
             */
            areaKm2: number | null;
            /**
             * @description İlçe sayısı.
             * @example 39
             */
            districtCount: number | null;
            /**
             * @description Nüfus yoğunluğu (kişi/km²) — SERVER-COMPUTED, not stored: round(nüfus / yüzölçümü). Null when population or area is null. Consume this rather than recomputing, so the rounding/null rule stays single-sourced.
             * @example 2885
             */
            populationDensity: number | null;
            /**
             * @description İl merkezi rakımı (m) — MGM il-merkez istasyonu referansı.
             * @example 33
             */
            elevationM: number | null;
            /**
             * @description İl merkezi enlemi (decimal degrees) — MGM il-merkez istasyonu.
             * @example 40.9819
             */
            latitude: number | null;
            /**
             * @description İl merkezi boylamı (decimal degrees) — MGM il-merkez istasyonu.
             * @example 28.8208
             */
            longitude: number | null;
            /**
             * @description Komşu illerin plaka kodları (hub-and-spoke için).
             * @example [
             *       "59",
             *       "41"
             *     ]
             */
            neighborPlateCodes: string[];
            /**
             * @description Köppen iklim kısa kodu (MGM 2023).
             * @example Csa
             */
            climateKoppen: string | null;
            /**
             * @description MGM Türkçe iklim sınıf adı.
             * @example Akdeniz iklimi
             */
            climateClassTr: string | null;
            /**
             * @description MGM Köppen metodolojik uyarı notu — Köppen değeriyle birlikte ZORUNLU olarak sunulur (bare bir 'Csa' yayınlanmaz).
             * @example MGM'nin 2023 Köppen sınıflandırması bu ili Csa (Akdeniz iklimi) olarak verir; ancak MGM'nin kendi raporu bu basitleştirilmiş yöntemin bölgesel ayırt ediciliğinin sınırlı olduğunu not düşer.
             */
            climateNoteTr: string | null;
            /** @description Öne çıkan yer şekilleri / jeoloji notu (TR). */
            landformNoteTr: string | null;
            /** @description Hidrografya — kısa düzyazı not (nehir/göl/baraj anlatısı, TR). */
            hydrographyNoteTr: string | null;
            /** @description Hidrografya — yapısal özellik listesi (baraj/nehir/göl). Null = araştırılmadı; boş dizi = "belirgin özellik yok" (bilinçli ifade). */
            hydrographyFeatures: components["schemas"]["HydrographyFeatureDto"][] | null;
            /**
             * @description Şehirleşme oranı (%) — TÜİK ADNKS (il/ilçe merkezi nüfusu / toplam).
             * @example 93.5
             */
            urbanizationRate: number | null;
            /**
             * @description Net göç hızı (‰) — TÜİK Göç İstatistikleri; işaretli (net göç ± olabilir).
             * @example 19.6
             */
            netMigrationRate: number | null;
            /** @description Nüfus ve yerleşme — kısa düzyazı not (TR). */
            settlementNoteTr: string | null;
            /** @description Ekonomik coğrafya — TEK, TÜİK-çıpalı yapısal istatistik (serbest metin değil). */
            economyIndicator: components["schemas"]["EconomyIndicatorDto"] | null;
            /**
             * Format: date-time
             * @description Kayıt oluşturulma zamanı.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Son güncelleme zamanı (SEO dateModified / sitemap lastmod).
             */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    ProvinceController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvinceListItemDto"][];
                };
            };
        };
    };
    ProvinceController_findMapSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvinceMapSummaryDto"][];
                };
            };
        };
    };
    ProvinceController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TR or EN slug of the province. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvinceDetailDto"];
                };
            };
            /** @description No province matches the given slug. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
