/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe — returns ok when the API is up. */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all provinces (lean payload for the il-hub + map). */
        get: operations["ProvinceController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces/map-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulk hover-card summary for all provinces (homepage SVG map, build-time embed). */
        get: operations["ProvinceController_findMapSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one province by its TR or EN slug (full detail). */
        get: operations["ProvinceController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all countries (lean payload for the /dunya hub + map). */
        get: operations["CountryController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries/map-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulk hover-card summary for all countries (world SVG map, build-time embed). */
        get: operations["CountryController_findMapSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one country by its TR or EN slug (full detail). */
        get: operations["CountryController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @description Liveness status of the API. Always "ok" when the service responds.
             * @example ok
             */
            status: string;
        };
        ProvinceListItemDto: {
            /**
             * @description Plaka kodu (stable, unique).
             * @example 34
             */
            plateCode: string;
            /**
             * @description İl adı (TR).
             * @example İstanbul
             */
            nameTr: string;
            /**
             * @description Coğrafi bölge.
             * @enum {string}
             */
            region: "MARMARA" | "EGE" | "AKDENIZ" | "IC_ANADOLU" | "KARADENIZ" | "DOGU_ANADOLU" | "GUNEYDOGU_ANADOLU";
            /**
             * @description TR slug (routing key).
             * @example istanbul
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example istanbul
             */
            slugEn: string;
            /**
             * @description Köppen iklim kısa kodu (MGM 2023). Liste DTO’suna bilinçli eklendi: "benzer iklime sahip iller" bloğu bu alan olmadan kurulamaz (aynı Köppen kodlu illere çapraz link). Saf toplama, kırıcı değil.
             * @example Csa
             */
            climateKoppen: string | null;
        };
        ProvinceMapSummaryDto: {
            /**
             * @description Plaka kodu (stable, unique).
             * @example 34
             */
            plateCode: string;
            /**
             * @description İl adı (TR).
             * @example İstanbul
             */
            nameTr: string;
            /**
             * @description Coğrafi bölge.
             * @enum {string}
             */
            region: "MARMARA" | "EGE" | "AKDENIZ" | "IC_ANADOLU" | "KARADENIZ" | "DOGU_ANADOLU" | "GUNEYDOGU_ANADOLU";
            /**
             * @description TR slug (routing key — kart tıklaması).
             * @example istanbul
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example istanbul
             */
            slugEn: string;
            /**
             * @description Nüfus (TÜİK ADNKS). Null until fact-checked.
             * @example 15754053
             */
            population: number | null;
            /**
             * @description Nüfus referans yılı.
             * @example 2025
             */
            populationYear: number | null;
            /**
             * @description Yüzölçümü (km², HGM).
             * @example 5461
             */
            areaKm2: number | null;
            /**
             * @description İlçe sayısı.
             * @example 39
             */
            districtCount: number | null;
        };
        ClimateMonthlyNormalDto: {
            /**
             * @description 1 = Ocak … 12 = Aralık.
             * @example 7
             */
            month: number;
            /**
             * @description Ortalama sıcaklık (°C). Çekirdek çift — yayınlanan her ilde doludur.
             * @example 27.9
             */
            tempMeanC: number | null;
            /**
             * @description Ortalama en yüksek sıcaklık (°C).
             * @example 33.2
             */
            tempMaxMeanC: number | null;
            /**
             * @description Ortalama en düşük sıcaklık (°C).
             * @example 22.6
             */
            tempMinMeanC: number | null;
            /**
             * @description Aylık toplam yağış miktarı ortalaması (mm). Çekirdek çift.
             * @example 4.7
             */
            precipitationMm: number | null;
            /**
             * @description Ortalama günlük güneşlenme süresi (saat).
             * @example 11.2
             */
            sunshineHours: number | null;
            /**
             * @description Ortalama yağışlı gün sayısı.
             * @example 2.1
             */
            rainyDays: number | null;
            /**
             * @description O ay ölçülmüş en yüksek sıcaklık (°C) — uç değer, ortalama değil.
             * @example 45.6
             */
            tempRecordMaxC: number | null;
            /**
             * Format: date
             * @description `tempRecordMaxC` gerçekleşme tarihi (ISO YYYY-MM-DD). Değerden bağımsız nullable.
             * @example 2000-07-30
             */
            tempRecordMaxDate: string | null;
            /**
             * @description O ay ölçülmüş en düşük sıcaklık (°C) — uç değer, ortalama değil.
             * @example 12.3
             */
            tempRecordMinC: number | null;
            /**
             * Format: date
             * @description `tempRecordMinC` gerçekleşme tarihi (ISO YYYY-MM-DD). Değerden bağımsız nullable.
             * @example 1976-07-05
             */
            tempRecordMinDate: string | null;
        };
        ClimateExtremeRecordDto: {
            /**
             * @description Ölçülen uç değer (ham sayı).
             * @example 189.4
             */
            value: number;
            /**
             * Format: date
             * @description Gerçekleşme tarihi (ISO YYYY-MM-DD). MGM tarihi basmadıysa null — değerden bağımsız nullable.
             * @example 1968-12-26
             */
            date: string | null;
        };
        ClimateRecordsDto: {
            /** @description Günlük toplam en yüksek yağış miktarı (mm). */
            dailyMaxPrecipitationMm: components["schemas"]["ClimateExtremeRecordDto"] | null;
            /** @description Günlük en hızlı rüzgâr (m/sn). */
            fastestWindMs: components["schemas"]["ClimateExtremeRecordDto"] | null;
            /** @description En yüksek kar yüksekliği (cm). */
            maxSnowDepthCm: components["schemas"]["ClimateExtremeRecordDto"] | null;
        };
        SeasonalPrecipitationDto: {
            /**
             * @description Kış (Ara+Oca+Şub) yağış payı (%).
             * @example 45
             */
            winterPct: number;
            /**
             * @description İlkbahar (Mar+Nis+May) yağış payı (%).
             * @example 27
             */
            springPct: number;
            /**
             * @description Yaz (Haz+Tem+Ağu) yağış payı (%).
             * @example 6
             */
            summerPct: number;
            /**
             * @description Sonbahar (Eyl+Eki+Kas) yağış payı (%).
             * @example 22
             */
            autumnPct: number;
        };
        ClimateDerivedDto: {
            /**
             * @description Yıllık ortalama sıcaklık (°C) — 12 aylık ortalamanın ortalaması (TÜRETİLMİŞ, MGM değil).
             * @example 19.1
             */
            annualMeanTempC: number;
            /**
             * @description Yıllık toplam yağış (mm) — 12 aylık toplamın toplamı (TÜRETİLMİŞ, MGM değil).
             * @example 592.4
             */
            annualPrecipitationMm: number;
            /**
             * @description En sıcak ay (1-12).
             * @example 8
             */
            hottestMonth: number;
            /**
             * @description En soğuk ay (1-12).
             * @example 1
             */
            coldestMonth: number;
            /**
             * @description En yağışlı ay (1-12).
             * @example 12
             */
            wettestMonth: number;
            /**
             * @description En kurak ay (1-12).
             * @example 7
             */
            driestMonth: number;
            /**
             * @description Yıllık sıcaklık farkı (°C) — en sıcak ile en soğuk ay ortalaması arası (TÜRETİLMİŞ).
             * @example 20.4
             */
            annualTempRangeC: number;
            /** @description Mevsimsel yağış yüzdeleri (tam 100 eder) — TÜRETİLMİŞ. */
            seasonalPrecipitation: components["schemas"]["SeasonalPrecipitationDto"];
        };
        ClimateDto: {
            /**
             * @description Kaynak seri kimliği — MGM Genel İstatistik tablosu (k=A), 81 il için tek seri.
             * @example mgm_general
             * @enum {string}
             */
            source: "mgm_general";
            /**
             * @description Bu serinin okunduğu MGM sayfası — il başına (MGM anahtarı Türkçe adla aynı değil).
             * @example https://www.mgm.gov.tr/veridegerlendirme/il-ve-ilceler-istatistik.aspx?k=A&m=ICEL
             */
            sourceUrl: string;
            /**
             * @description Ölçüm periyodu başlangıç yılı — il başına değişir, sayfadan okunur.
             * @example 1929
             */
            periodStartYear: number;
            /**
             * @description Ölçüm periyodu bitiş yılı.
             * @example 2025
             */
            periodEndYear: number;
            /** @description Aylık normaller — tam 12 ay, 1-12 sırasıyla. */
            months: components["schemas"]["ClimateMonthlyNormalDto"][];
            /** @description Tüm zamanların rekorları. */
            records: components["schemas"]["ClimateRecordsDto"];
            /** @description Seriden TÜRETİLMİŞ yıllık/uç/mevsimsel değerler — MGM’e atfedilemez. */
            derived: components["schemas"]["ClimateDerivedDto"];
        };
        HydrographyFeatureDto: {
            /**
             * @description Öz ad.
             * @example Ömerli Barajı
             */
            name: string;
            /**
             * @description Özellik türü (baraj/nehir/göl) — ASCII değer; TR etiketi web tarafında.
             * @example baraj
             * @enum {string}
             */
            type: "baraj" | "nehir" | "gol";
        };
        EconomyIndicatorDto: {
            /**
             * @description İstatistiğin ölçtüğü büyüklük.
             * @example GSYH'de Türkiye payı
             */
            label: string;
            /**
             * @description Değer, string — pay/sıra/ürün adı olabildiği için (heterojen).
             * @example %30,2
             */
            value: string;
            /**
             * @description İstatistiğin referans yılı.
             * @example 2024
             */
            year: number;
            /**
             * @description Otoriter kaynak.
             * @example TÜİK Bölgesel GSYH
             */
            source: string;
        };
        ProvinceDetailDto: {
            /**
             * @description Plaka kodu.
             * @example 34
             */
            plateCode: string;
            /**
             * @description İl adı (TR).
             * @example İstanbul
             */
            nameTr: string;
            /**
             * @description TR slug (routing key).
             * @example istanbul
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example istanbul
             */
            slugEn: string;
            /**
             * @description Coğrafi bölge.
             * @enum {string}
             */
            region: "MARMARA" | "EGE" | "AKDENIZ" | "IC_ANADOLU" | "KARADENIZ" | "DOGU_ANADOLU" | "GUNEYDOGU_ANADOLU";
            /**
             * @description Yazılı açılış cümlesi (il girişi). Null ise web veri-tabanlı bir cümle kurar (fallback).
             * @example İstanbul, Karadeniz ile Marmara Denizi'ni birbirine bağlayan Boğaz'ın iki yakasına kurulmuştur.
             */
            introTr: string | null;
            /**
             * @description Nüfus (TÜİK ADNKS). Null until fact-checked.
             * @example 15754053
             */
            population: number | null;
            /**
             * @description Nüfus referans yılı.
             * @example 2025
             */
            populationYear: number | null;
            /**
             * @description Yüzölçümü (km², HGM).
             * @example 5461
             */
            areaKm2: number | null;
            /**
             * @description İlçe sayısı.
             * @example 39
             */
            districtCount: number | null;
            /**
             * @description Nüfus yoğunluğu (kişi/km²) — SERVER-COMPUTED, not stored: round(nüfus / yüzölçümü). Null when population or area is null. Consume this rather than recomputing, so the rounding/null rule stays single-sourced.
             * @example 2885
             */
            populationDensity: number | null;
            /**
             * @description İl merkezi rakımı (m) — MGM il-merkez istasyonu referansı.
             * @example 33
             */
            elevationM: number | null;
            /**
             * @description İl merkezi enlemi (decimal degrees) — MGM il-merkez istasyonu.
             * @example 40.9819
             */
            latitude: number | null;
            /**
             * @description İl merkezi boylamı (decimal degrees) — MGM il-merkez istasyonu.
             * @example 28.8208
             */
            longitude: number | null;
            /**
             * @description Komşu illerin plaka kodları (hub-and-spoke için).
             * @example [
             *       "59",
             *       "41"
             *     ]
             */
            neighborPlateCodes: string[];
            /**
             * @description Köppen iklim kısa kodu (MGM 2023).
             * @example Csa
             */
            climateKoppen: string | null;
            /**
             * @description MGM Türkçe iklim sınıf adı.
             * @example Akdeniz iklimi
             */
            climateClassTr: string | null;
            /**
             * @description MGM Köppen metodolojik uyarı notu — Köppen değeriyle birlikte ZORUNLU olarak sunulur (bare bir 'Csa' yayınlanmaz).
             * @example MGM'nin 2023 Köppen sınıflandırması bu ili Csa (Akdeniz iklimi) olarak verir; ancak MGM'nin kendi raporu bu basitleştirilmiş yöntemin bölgesel ayırt ediciliğinin sınırlı olduğunu not düşer.
             */
            climateNoteTr: string | null;
            /** @description İklim serisi (MGM k=A aylık normalleri + kaynak/dönem/rekorlar) + TÜRETİLMİŞ yıllık/mevsimsel değerler. Null = yayınlanabilir seri yok → web iklim bölümünü hiç render etmez. Türetilmiş değerler bizimdir, MGM'e atfedilemez; tüm sayılar ham (biçimlendirme web'in işi). */
            climate: components["schemas"]["ClimateDto"] | null;
            /** @description NOVA'nın il-il yazdığı iklim yorumu (TR) — mekanizma anlatan gerçek düzyazı. `climateNoteTr` (kilitli MGM Köppen uyarısı) DEĞİL; ayrı bir alandır. İçerik dalgaları doldurana kadar null. */
            climateNarrativeTr: string | null;
            /** @description Öne çıkan yer şekilleri / jeoloji notu (TR). */
            landformNoteTr: string | null;
            /** @description Hidrografya — kısa düzyazı not (nehir/göl/baraj anlatısı, TR). */
            hydrographyNoteTr: string | null;
            /** @description Hidrografya — yapısal özellik listesi (baraj/nehir/göl). Null = araştırılmadı; boş dizi = "belirgin özellik yok" (bilinçli ifade). */
            hydrographyFeatures: components["schemas"]["HydrographyFeatureDto"][] | null;
            /**
             * @description Şehirleşme oranı (%) — TÜİK ADNKS (il/ilçe merkezi nüfusu / toplam).
             * @example 93.5
             */
            urbanizationRate: number | null;
            /**
             * @description Net göç hızı (‰) — TÜİK Göç İstatistikleri; işaretli (net göç ± olabilir).
             * @example 19.6
             */
            netMigrationRate: number | null;
            /** @description Nüfus ve yerleşme — kısa düzyazı not (TR). */
            settlementNoteTr: string | null;
            /** @description Ekonomik coğrafya — TEK, TÜİK-çıpalı yapısal istatistik (serbest metin değil). */
            economyIndicator: components["schemas"]["EconomyIndicatorDto"] | null;
            /**
             * Format: date-time
             * @description Kayıt oluşturulma zamanı.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Son güncelleme zamanı (SEO dateModified / sitemap lastmod).
             */
            updatedAt: string;
        };
        CountryListItemDto: {
            /**
             * @description ISO 3166-1 alpha-2 kodu (stable, unique).
             * @example TR
             */
            isoCode: string;
            /**
             * @description Ülke adı (TR).
             * @example Türkiye
             */
            nameTr: string;
            /**
             * @description Ülke adı (EN).
             * @example Türkiye
             */
            nameEn: string;
            /**
             * @description Kıta.
             * @enum {string}
             */
            continent: "ASYA" | "AVRUPA" | "AFRIKA" | "KUZEY_AMERIKA" | "GUNEY_AMERIKA" | "OKYANUSYA";
            /**
             * @description TR slug (routing key).
             * @example turkiye
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example turkey
             */
            slugEn: string;
        };
        CountryMapSummaryDto: {
            /**
             * @description ISO 3166-1 alpha-2 kodu (stable, unique).
             * @example TR
             */
            isoCode: string;
            /**
             * @description Ülke adı (TR).
             * @example Türkiye
             */
            nameTr: string;
            /**
             * @description Ülke adı (EN).
             * @example Türkiye
             */
            nameEn: string;
            /**
             * @description Kıta.
             * @enum {string}
             */
            continent: "ASYA" | "AVRUPA" | "AFRIKA" | "KUZEY_AMERIKA" | "GUNEY_AMERIKA" | "OKYANUSYA";
            /**
             * @description TR slug (routing key — kart tıklaması).
             * @example turkiye
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example turkey
             */
            slugEn: string;
            /**
             * @description Nüfus (World Bank / UN). Null until fact-checked.
             * @example 85372000
             */
            population: number | null;
            /**
             * @description Nüfus referans yılı.
             * @example 2024
             */
            populationYear: number | null;
            /**
             * @description Yüzölçümü (km², World Bank / UN).
             * @example 783562
             */
            areaKm2: number | null;
            /**
             * @description Komşu ülke sayısı — SERVER-DERIVED from the neighbour ISO-code array length (the "ilçe sayısı" replacement). Always present (0 for island nations).
             * @example 8
             */
            neighborCount: number;
        };
        CountryDetailDto: {
            /**
             * @description ISO 3166-1 alpha-2 kodu.
             * @example TR
             */
            isoCode: string;
            /**
             * @description ISO 3166-1 alpha-3 kodu (ikincil tanımlayıcı).
             * @example TUR
             */
            isoCodeAlpha3: string | null;
            /**
             * @description Ülke adı (TR).
             * @example Türkiye
             */
            nameTr: string;
            /**
             * @description Ülke adı (EN).
             * @example Türkiye
             */
            nameEn: string;
            /**
             * @description TR slug (routing key).
             * @example turkiye
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example turkey
             */
            slugEn: string;
            /**
             * @description Kıta.
             * @enum {string}
             */
            continent: "ASYA" | "AVRUPA" | "AFRIKA" | "KUZEY_AMERIKA" | "GUNEY_AMERIKA" | "OKYANUSYA";
            /**
             * @description BM alt-bölgesi (UNSD M49) TR etiketi.
             * @example Batı Asya
             */
            unSubregionTr: string | null;
            /**
             * @description Yazılı açılış cümlesi (ülke girişi). Null ise web veri-tabanlı bir cümle kurar.
             * @example Türkiye, Asya ile Avrupa'yı birbirine bağlayan, üç tarafı denizlerle çevrili bir ülkedir.
             */
            introTr: string | null;
            /**
             * @description Nüfus (World Bank / UN). Null until fact-checked.
             * @example 85372000
             */
            population: number | null;
            /**
             * @description Nüfus referans yılı.
             * @example 2024
             */
            populationYear: number | null;
            /**
             * @description Yüzölçümü (km², World Bank / UN).
             * @example 783562
             */
            areaKm2: number | null;
            /**
             * @description Komşu ülke sayısı — SERVER-DERIVED: neighbour ISO-code array length (the "ilçe sayısı" replacement). Consume this rather than recomputing. Always present (0 for island nations).
             * @example 8
             */
            neighborCount: number;
            /**
             * @description Komşu ülkelerin ISO 3166-1 alpha-2 kodları (hub-and-spoke için).
             * @example [
             *       "GR",
             *       "BG",
             *       "GE",
             *       "AM",
             *       "AZ",
             *       "IR",
             *       "IQ",
             *       "SY"
             *     ]
             */
            neighborIsoCodes: string[];
            /**
             * @description Başkent adı (TR).
             * @example Ankara
             */
            capitalNameTr: string | null;
            /**
             * @description Başkent adı (EN).
             * @example Ankara
             */
            capitalNameEn: string | null;
            /**
             * @description Başkent enlemi (decimal degrees).
             * @example 39.9334
             */
            capitalLatitude: number | null;
            /**
             * @description Başkent boylamı (decimal degrees).
             * @example 32.8597
             */
            capitalLongitude: number | null;
            /**
             * @description Resmi dil(ler) (TR dil adları). Null = araştırılmadı.
             * @example [
             *       "Türkçe"
             *     ]
             */
            officialLanguagesTr: string[] | null;
            /**
             * @description Para birimi adı (TR).
             * @example Türk lirası
             */
            currencyNameTr: string | null;
            /**
             * @description Para birimi kodu (ISO 4217).
             * @example TRY
             */
            currencyCode: string | null;
            /**
             * @description Yönetim biçimi (TR).
             * @example Üniter başkanlık cumhuriyeti
             */
            governmentFormTr: string | null;
            /**
             * @description Bağımsızlık tarihi / notu (serbest metin, yapılandırılmış tarih değil).
             * @example 29 Ekim 1923
             */
            independenceNoteTr: string | null;
            /** @description Öne çıkan yer şekilleri / jeoloji notu (TR). */
            landformNoteTr: string | null;
            /** @description İklim — serbest anlatı düzyazısı (ülke içi bölgesel iklim çeşitliliği). Yapılandırılmış Köppen kodu DEĞİL (ülke ölçeğinde tek kod yanıltıcı olur). */
            climateNoteTr: string | null;
            /** @description Hidrografya — kısa düzyazı not (nehir/göl/deniz anlatısı, TR). */
            hydrographyNoteTr: string | null;
            /** @description Egemenlik / uluslararası tanınma çerçevesi — serbest anlatı düzyazısı (TR). Yalnızca tanınma statüsü tartışmalı/standart-dışı ülkeler için doldurulur; sıradan ülkelerde null. */
            sovereigntyNoteTr: string | null;
            /**
             * Format: date-time
             * @description Kayıt oluşturulma zamanı.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Son güncelleme zamanı (SEO dateModified / sitemap lastmod).
             */
            updatedAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    ProvinceController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvinceListItemDto"][];
                };
            };
        };
    };
    ProvinceController_findMapSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvinceMapSummaryDto"][];
                };
            };
        };
    };
    ProvinceController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TR or EN slug of the province. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvinceDetailDto"];
                };
            };
            /** @description No province matches the given slug. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CountryController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryListItemDto"][];
                };
            };
        };
    };
    CountryController_findMapSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryMapSummaryDto"][];
                };
            };
        };
    };
    CountryController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TR or EN slug of the country. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryDetailDto"];
                };
            };
            /** @description No country matches the given slug. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
