/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe — returns ok when the API is up. */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all provinces (lean payload for the il-hub + map). */
        get: operations["ProvinceController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces/map-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulk hover-card summary for all provinces (homepage SVG map, build-time embed). */
        get: operations["ProvinceController_findMapSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provinces/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one province by its TR or EN slug (full detail). */
        get: operations["ProvinceController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all countries (lean payload for the /dunya hub + map). */
        get: operations["CountryController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries/map-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulk hover-card summary for all countries (world SVG map, build-time embed). */
        get: operations["CountryController_findMapSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one country by its TR or EN slug (full detail). */
        get: operations["CountryController_findBySlug"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marine/points": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every marine reference point (lean payload for the /deniz hub + map).
         * @description Plain array, bounded and small. Points are OFFSHORE coordinates deliberately outside straits and narrow gulfs, where regional models measurably disagree; the three two-sea provinces (İstanbul, Çanakkale, Balıkesir) each return two entries.
         */
        get: operations["MarineController_findAllPoints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marine/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Layer catalogue — units, direction conventions, calm thresholds, colour ramps.
         * @description The machine-readable authority for how a value may be rendered. In particular directionConvention states, per layer, whether a degree means the direction the flow comes FROM or heads TOWARDS — the providers use both, inside the same API. Both arrow-unlock preconditions are met for the wind layers (the field is published and the wind-convention regression suite runs on CI). For the two ECMWF-PRIMARY layers (wind_speed_10m, wind_direction_10m), horizonEndUtc / updateFrequency / catalogueUpdatedAtUtc are resolved from the newest ingested model cycle — a local database read; this endpoint NEVER calls a provider. They are null while no cycle has been ingested yet or the newest one breached the 24 h cycle-age ceiling. The three CMEMS-primary layers resolve the same fields from the stored STAC catalogue resolutions the warmup tour maintains — also a local cache read, never a provider call; they are null while no resolution is stored yet (cold cache) or not every serving product is resolved (a partial horizon minimum could overstate the horizon).
         */
        get: operations["MarineController_findAllLayers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marine/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Instant marine values for every reference point (the /deniz hub payload).
         * @description CMEMS-sourced fields are answered from cache only — this endpoint NEVER waits for a provider. dataAvailable=false (cold cache) responses carry Cache-Control: no-store and MUST NOT be committed by ISR/SSG. Returns 404 while the marine feature is disabled.
         */
        get: operations["MarineController_getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marine/points/{slug}/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Instant values and the 5-day series for one marine reference point.
         * @description The slug may be the TR or the EN one (both are routing keys). A cold cache may refresh this point’s own CMEMS values inline under one bounded deadline; a provider failure degrades the affected fields to unavailable, never the response.
         */
        get: operations["MarineController_getConditions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marine/provinces/{plateCode}/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Marine conditions of every reference point published under one province.
         * @description Two entries for the two-sea provinces (İstanbul, Çanakkale, Balıkesir); the entries legitimately disagree and each carries its own per-field statuses — one point’s outage never suppresses or fills the other. An inland province is a 404.
         */
        get: operations["MarineController_getProvinceConditions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/air-quality/index-system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full machine-readable definition of the active air-quality index system.
         * @description The published methodology behind every band/category this API serves: the EAQI-2024 band table (EEA/ETC HE 2024/17, Table 5.2), the (lo, hi] boundary rule as a token, per-pollutant averaging periods (all hourly) and the dominant-pollutant tie-break order. The web repo renders from THIS payload and hardcodes none of it. Served from an in-code constant: answers 200 cold or warm and never calls the upstream provider.
         */
        get: operations["AirQualityController_getIndexSystem"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/air-quality/provinces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Instant air-quality state of every province (the /hava hub payload).
         * @description Plain array, bounded and small — one entry per province, in plate order, ALWAYS. On the cold path every entry carries status=unavailable and the response is Cache-Control: no-store, which ISR/SSG must not commit. This endpoint reads the local store only and NEVER waits for the provider. Band and category are TOKENS: the band table behind them is published at GET /api/air-quality/index-system and must not be hardcoded.
         */
        get: operations["AirQualityController_listProvinces"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/air-quality/provinces/{plateCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full air-quality state and the hourly series for one province.
         * @description Answers 200 in every state: with no usable run the payload carries current.status=unavailable, series=null, dataAvailable=false and Cache-Control: no-store. The series concatenates the provider ANALYSIS product (steps before analysisEndUtc) with the FORECAST product (from analysisEndUtc onward); both halves are model output on a ~0.1° grid, neither is a station reading. A plate code that names no province is a 404. This endpoint never waits for the provider.
         */
        get: operations["AirQualityController_getProvince"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @description Liveness status of the API. Always "ok" when the service responds.
             * @example ok
             */
            status: string;
        };
        ProvinceListItemDto: {
            /**
             * @description Plaka kodu (stable, unique).
             * @example 34
             */
            plateCode: string;
            /**
             * @description İl adı (TR).
             * @example İstanbul
             */
            nameTr: string;
            /**
             * @description Coğrafi bölge.
             * @enum {string}
             */
            region: "MARMARA" | "EGE" | "AKDENIZ" | "IC_ANADOLU" | "KARADENIZ" | "DOGU_ANADOLU" | "GUNEYDOGU_ANADOLU";
            /**
             * @description TR slug (routing key).
             * @example istanbul
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example istanbul
             */
            slugEn: string;
            /**
             * @description Köppen iklim kısa kodu (MGM 2023). Liste DTO’suna bilinçli eklendi: "benzer iklime sahip iller" bloğu bu alan olmadan kurulamaz (aynı Köppen kodlu illere çapraz link). Saf toplama, kırıcı değil.
             * @example Csa
             */
            climateKoppen: string | null;
            /**
             * @description Yıllık ortalama sıcaklık (°C) — 12 aylık ortalamanın ortalaması, 1 ondalık. Detay DTO’sundaki climate.derived.annualMeanTempC ile AYNI türetilmiş değerdir (tek kaynak: climate-derivations.ts; liste yolunda yeniden türetilmez, aynı buildClimate çağrısıyla canlı hesaplanır). Benzer-iklim bloğunun "en yakın 5" seçimi (→ DEC 2026-07-20b) ve çapa metnindeki "il adı + °C" bu alan olmadan kurulamaz. İlin yayınlanabilir iklim serisi yoksa null. Saf toplama, kırıcı değil.
             * @example 14.2
             */
            climateAnnualMeanTempC: number | null;
        };
        ProvinceMapSummaryDto: {
            /**
             * @description Plaka kodu (stable, unique).
             * @example 34
             */
            plateCode: string;
            /**
             * @description İl adı (TR).
             * @example İstanbul
             */
            nameTr: string;
            /**
             * @description Coğrafi bölge.
             * @enum {string}
             */
            region: "MARMARA" | "EGE" | "AKDENIZ" | "IC_ANADOLU" | "KARADENIZ" | "DOGU_ANADOLU" | "GUNEYDOGU_ANADOLU";
            /**
             * @description TR slug (routing key — kart tıklaması).
             * @example istanbul
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example istanbul
             */
            slugEn: string;
            /**
             * @description Nüfus (TÜİK ADNKS). Null until fact-checked.
             * @example 15754053
             */
            population: number | null;
            /**
             * @description Nüfus referans yılı.
             * @example 2025
             */
            populationYear: number | null;
            /**
             * @description Yüzölçümü (km², HGM).
             * @example 5461
             */
            areaKm2: number | null;
            /**
             * @description İlçe sayısı.
             * @example 39
             */
            districtCount: number | null;
        };
        ClimateMonthlyNormalDto: {
            /**
             * @description 1 = Ocak … 12 = Aralık.
             * @example 7
             */
            month: number;
            /**
             * @description 30 yıllık (1991-2020) aylık ortalama sıcaklık (°C). Çekirdek çift — her yayınlanan ilde doludur.
             * @example 24.1
             */
            tempMeanC: number;
            /**
             * @description 30 yıllık (1991-2020) aylık toplam yağış ortalaması (mm). Çekirdek çift — her yayınlanan ilde doludur.
             * @example 21.5
             */
            precipitationMm: number;
        };
        SeasonalPrecipitationDto: {
            /**
             * @description Kış (Ara+Oca+Şub) yağış payı (%).
             * @example 45
             */
            winterPct: number;
            /**
             * @description İlkbahar (Mar+Nis+May) yağış payı (%).
             * @example 27
             */
            springPct: number;
            /**
             * @description Yaz (Haz+Tem+Ağu) yağış payı (%).
             * @example 6
             */
            summerPct: number;
            /**
             * @description Sonbahar (Eyl+Eki+Kas) yağış payı (%).
             * @example 22
             */
            autumnPct: number;
        };
        ClimateDerivedDto: {
            /**
             * @description Yıllık ortalama sıcaklık (°C) — 12 aylık ortalamanın ortalaması (TÜRETİLMİŞ; kaynağa atfedilemez).
             * @example 14.7
             */
            annualMeanTempC: number;
            /**
             * @description Yıllık toplam yağış (mm) — 12 aylık toplamın toplamı (TÜRETİLMİŞ; kaynağa atfedilemez).
             * @example 630.2
             */
            annualPrecipitationMm: number;
            /**
             * @description En sıcak ay (1-12).
             * @example 8
             */
            hottestMonth: number;
            /**
             * @description En soğuk ay (1-12).
             * @example 1
             */
            coldestMonth: number;
            /**
             * @description En yağışlı ay (1-12).
             * @example 12
             */
            wettestMonth: number;
            /**
             * @description En kurak ay (1-12).
             * @example 7
             */
            driestMonth: number;
            /**
             * @description Yıllık sıcaklık farkı (°C) — en sıcak ile en soğuk ay ortalaması arası (TÜRETİLMİŞ).
             * @example 18.3
             */
            annualTempRangeC: number;
            /** @description Mevsimsel yağış yüzdeleri (tam 100 eder) — TÜRETİLMİŞ. */
            seasonalPrecipitation: components["schemas"]["SeasonalPrecipitationDto"];
        };
        ClimateDto: {
            /**
             * @description Kaynak seri kimliği — Copernicus C3S ERA5-Land aylık ortalamaları, 81 il için tek dataset.
             * @example era5_land_monthly
             * @enum {string}
             */
            source: "era5_land_monthly";
            /**
             * @description Serinin türetildiği ERA5-Land dataset sayfası — 81 ilde AYNI sabit değer (il başına sayfa yoktur).
             * @example https://cds.climate.copernicus.eu/datasets/reanalysis-era5-land-monthly-means
             */
            sourceUrl: string;
            /**
             * @description Normal penceresi başlangıç yılı — WMO 1991-2020, 81 ilde sabit.
             * @example 1991
             */
            periodStartYear: number;
            /**
             * @description Normal penceresi bitiş yılı — WMO 1991-2020, 81 ilde sabit.
             * @example 2020
             */
            periodEndYear: number;
            /** @description Aylık normaller — tam 12 ay, 1-12 sırasıyla. */
            months: components["schemas"]["ClimateMonthlyNormalDto"][];
            /** @description Seriden TÜRETİLMİŞ yıllık/uç/mevsimsel değerler — kaynağa atfedilemez. */
            derived: components["schemas"]["ClimateDerivedDto"];
        };
        HydrographyFeatureDto: {
            /**
             * @description Öz ad.
             * @example Ömerli Barajı
             */
            name: string;
            /**
             * @description Özellik türü (baraj/nehir/göl) — ASCII değer; TR etiketi web tarafında.
             * @example baraj
             * @enum {string}
             */
            type: "baraj" | "nehir" | "gol";
        };
        EconomyIndicatorDto: {
            /**
             * @description İstatistiğin ölçtüğü büyüklük.
             * @example GSYH'de Türkiye payı
             */
            label: string;
            /**
             * @description Değer, string — pay/sıra/ürün adı olabildiği için (heterojen).
             * @example %30,2
             */
            value: string;
            /**
             * @description İstatistiğin referans yılı.
             * @example 2024
             */
            year: number;
            /**
             * @description Otoriter kaynak.
             * @example TÜİK Bölgesel GSYH
             */
            source: string;
        };
        ProvinceDetailDto: {
            /**
             * @description Plaka kodu.
             * @example 34
             */
            plateCode: string;
            /**
             * @description İl adı (TR).
             * @example İstanbul
             */
            nameTr: string;
            /**
             * @description TR slug (routing key).
             * @example istanbul
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example istanbul
             */
            slugEn: string;
            /**
             * @description Coğrafi bölge.
             * @enum {string}
             */
            region: "MARMARA" | "EGE" | "AKDENIZ" | "IC_ANADOLU" | "KARADENIZ" | "DOGU_ANADOLU" | "GUNEYDOGU_ANADOLU";
            /**
             * @description Yazılı açılış cümlesi (il girişi). Null ise web veri-tabanlı bir cümle kurar (fallback).
             * @example İstanbul, Karadeniz ile Marmara Denizi'ni birbirine bağlayan Boğaz'ın iki yakasına kurulmuştur.
             */
            introTr: string | null;
            /**
             * @description Nüfus (TÜİK ADNKS). Null until fact-checked.
             * @example 15754053
             */
            population: number | null;
            /**
             * @description Nüfus referans yılı.
             * @example 2025
             */
            populationYear: number | null;
            /**
             * @description Yüzölçümü (km², HGM).
             * @example 5461
             */
            areaKm2: number | null;
            /**
             * @description İlçe sayısı.
             * @example 39
             */
            districtCount: number | null;
            /**
             * @description Nüfus yoğunluğu (kişi/km²) — SERVER-COMPUTED, not stored: round(nüfus / yüzölçümü). Null when population or area is null. Consume this rather than recomputing, so the rounding/null rule stays single-sourced.
             * @example 2885
             */
            populationDensity: number | null;
            /**
             * @description İl merkezi rakımı (m) — MGM il-merkez istasyonu referansı.
             * @example 33
             */
            elevationM: number | null;
            /**
             * @description İl merkezi enlemi (decimal degrees) — MGM il-merkez istasyonu.
             * @example 40.9819
             */
            latitude: number | null;
            /**
             * @description İl merkezi boylamı (decimal degrees) — MGM il-merkez istasyonu.
             * @example 28.8208
             */
            longitude: number | null;
            /**
             * @description Komşu illerin plaka kodları (hub-and-spoke için).
             * @example [
             *       "59",
             *       "41"
             *     ]
             */
            neighborPlateCodes: string[];
            /**
             * @description Köppen iklim kısa kodu (MGM 2023).
             * @example Csa
             */
            climateKoppen: string | null;
            /**
             * @description MGM Türkçe iklim sınıf adı.
             * @example Akdeniz iklimi
             */
            climateClassTr: string | null;
            /**
             * @description MGM Köppen metodolojik uyarı notu — Köppen değeriyle birlikte ZORUNLU olarak sunulur (bare bir 'Csa' yayınlanmaz).
             * @example MGM'nin 2023 Köppen sınıflandırması bu ili Csa (Akdeniz iklimi) olarak verir; ancak MGM'nin kendi raporu bu basitleştirilmiş yöntemin bölgesel ayırt ediciliğinin sınırlı olduğunu not düşer.
             */
            climateNoteTr: string | null;
            /** @description İklim serisi (ERA5-Land 1991-2020 aylık normalleri + kaynak/dönem) + TÜRETİLMİŞ yıllık/mevsimsel değerler. Null = yayınlanabilir seri yok → web iklim bölümünü hiç render etmez. Türetilmiş değerler bizimdir, kaynağa atfedilemez; tüm sayılar ham (biçimlendirme web'in işi). */
            climate: components["schemas"]["ClimateDto"] | null;
            /** @description NOVA'nın il-il yazdığı iklim yorumu (TR) — mekanizma anlatan gerçek düzyazı. `climateNoteTr` (kilitli MGM Köppen uyarısı) DEĞİL; ayrı bir alandır. İçerik dalgaları doldurana kadar null. */
            climateNarrativeTr: string | null;
            /** @description Öne çıkan yer şekilleri / jeoloji notu (TR). */
            landformNoteTr: string | null;
            /** @description Hidrografya — kısa düzyazı not (nehir/göl/baraj anlatısı, TR). */
            hydrographyNoteTr: string | null;
            /** @description Hidrografya — yapısal özellik listesi (baraj/nehir/göl). Null = araştırılmadı; boş dizi = "belirgin özellik yok" (bilinçli ifade). */
            hydrographyFeatures: components["schemas"]["HydrographyFeatureDto"][] | null;
            /**
             * @description Şehirleşme oranı (%) — TÜİK ADNKS (il/ilçe merkezi nüfusu / toplam).
             * @example 93.5
             */
            urbanizationRate: number | null;
            /**
             * @description Net göç hızı (‰) — TÜİK Göç İstatistikleri; işaretli (net göç ± olabilir).
             * @example 19.6
             */
            netMigrationRate: number | null;
            /** @description Nüfus ve yerleşme — kısa düzyazı not (TR). */
            settlementNoteTr: string | null;
            /** @description Ekonomik coğrafya — TEK, TÜİK-çıpalı yapısal istatistik (serbest metin değil). */
            economyIndicator: components["schemas"]["EconomyIndicatorDto"] | null;
            /**
             * Format: date-time
             * @description Kayıt oluşturulma zamanı.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Son güncelleme zamanı (SEO dateModified / sitemap lastmod).
             */
            updatedAt: string;
        };
        CountryListItemDto: {
            /**
             * @description ISO 3166-1 alpha-2 kodu (stable, unique).
             * @example TR
             */
            isoCode: string;
            /**
             * @description Ülke adı (TR).
             * @example Türkiye
             */
            nameTr: string;
            /**
             * @description Ülke adı (EN).
             * @example Türkiye
             */
            nameEn: string;
            /**
             * @description Kıta.
             * @enum {string}
             */
            continent: "ASYA" | "AVRUPA" | "AFRIKA" | "KUZEY_AMERIKA" | "GUNEY_AMERIKA" | "OKYANUSYA";
            /**
             * @description TR slug (routing key).
             * @example turkiye
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example turkey
             */
            slugEn: string;
        };
        CountryMapSummaryDto: {
            /**
             * @description ISO 3166-1 alpha-2 kodu (stable, unique).
             * @example TR
             */
            isoCode: string;
            /**
             * @description Ülke adı (TR).
             * @example Türkiye
             */
            nameTr: string;
            /**
             * @description Ülke adı (EN).
             * @example Türkiye
             */
            nameEn: string;
            /**
             * @description Kıta.
             * @enum {string}
             */
            continent: "ASYA" | "AVRUPA" | "AFRIKA" | "KUZEY_AMERIKA" | "GUNEY_AMERIKA" | "OKYANUSYA";
            /**
             * @description TR slug (routing key — kart tıklaması).
             * @example turkiye
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example turkey
             */
            slugEn: string;
            /**
             * @description Nüfus (World Bank / UN). Null until fact-checked.
             * @example 85372000
             */
            population: number | null;
            /**
             * @description Nüfus referans yılı.
             * @example 2024
             */
            populationYear: number | null;
            /**
             * @description Yüzölçümü (km², World Bank / UN).
             * @example 783562
             */
            areaKm2: number | null;
            /**
             * @description Komşu ülke sayısı — SERVER-DERIVED from the neighbour ISO-code array length (the "ilçe sayısı" replacement). Always present (0 for island nations).
             * @example 8
             */
            neighborCount: number;
        };
        CountryDetailDto: {
            /**
             * @description ISO 3166-1 alpha-2 kodu.
             * @example TR
             */
            isoCode: string;
            /**
             * @description ISO 3166-1 alpha-3 kodu (ikincil tanımlayıcı).
             * @example TUR
             */
            isoCodeAlpha3: string | null;
            /**
             * @description Ülke adı (TR).
             * @example Türkiye
             */
            nameTr: string;
            /**
             * @description Ülke adı (EN).
             * @example Türkiye
             */
            nameEn: string;
            /**
             * @description TR slug (routing key).
             * @example turkiye
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example turkey
             */
            slugEn: string;
            /**
             * @description Kıta.
             * @enum {string}
             */
            continent: "ASYA" | "AVRUPA" | "AFRIKA" | "KUZEY_AMERIKA" | "GUNEY_AMERIKA" | "OKYANUSYA";
            /**
             * @description BM alt-bölgesi (UNSD M49) TR etiketi.
             * @example Batı Asya
             */
            unSubregionTr: string | null;
            /**
             * @description Yazılı açılış cümlesi (ülke girişi). Null ise web veri-tabanlı bir cümle kurar.
             * @example Türkiye, Asya ile Avrupa'yı birbirine bağlayan, üç tarafı denizlerle çevrili bir ülkedir.
             */
            introTr: string | null;
            /**
             * @description Nüfus (World Bank / UN). Null until fact-checked.
             * @example 85372000
             */
            population: number | null;
            /**
             * @description Nüfus referans yılı.
             * @example 2024
             */
            populationYear: number | null;
            /**
             * @description Yüzölçümü (km², World Bank / UN).
             * @example 783562
             */
            areaKm2: number | null;
            /**
             * @description Komşu ülke sayısı — SERVER-DERIVED: neighbour ISO-code array length (the "ilçe sayısı" replacement). Consume this rather than recomputing. Always present (0 for island nations).
             * @example 8
             */
            neighborCount: number;
            /**
             * @description Komşu ülkelerin ISO 3166-1 alpha-2 kodları (hub-and-spoke için).
             * @example [
             *       "GR",
             *       "BG",
             *       "GE",
             *       "AM",
             *       "AZ",
             *       "IR",
             *       "IQ",
             *       "SY"
             *     ]
             */
            neighborIsoCodes: string[];
            /**
             * @description Başkent adı (TR).
             * @example Ankara
             */
            capitalNameTr: string | null;
            /**
             * @description Başkent adı (EN).
             * @example Ankara
             */
            capitalNameEn: string | null;
            /**
             * @description Başkent enlemi (decimal degrees).
             * @example 39.9334
             */
            capitalLatitude: number | null;
            /**
             * @description Başkent boylamı (decimal degrees).
             * @example 32.8597
             */
            capitalLongitude: number | null;
            /**
             * @description Resmi dil(ler) (TR dil adları). Null = araştırılmadı.
             * @example [
             *       "Türkçe"
             *     ]
             */
            officialLanguagesTr: string[] | null;
            /**
             * @description Para birimi adı (TR).
             * @example Türk lirası
             */
            currencyNameTr: string | null;
            /**
             * @description Para birimi kodu (ISO 4217).
             * @example TRY
             */
            currencyCode: string | null;
            /**
             * @description Yönetim biçimi (TR).
             * @example Üniter başkanlık cumhuriyeti
             */
            governmentFormTr: string | null;
            /**
             * @description Bağımsızlık tarihi / notu (serbest metin, yapılandırılmış tarih değil).
             * @example 29 Ekim 1923
             */
            independenceNoteTr: string | null;
            /** @description Öne çıkan yer şekilleri / jeoloji notu (TR). */
            landformNoteTr: string | null;
            /** @description İklim — serbest anlatı düzyazısı (ülke içi bölgesel iklim çeşitliliği). Yapılandırılmış Köppen kodu DEĞİL (ülke ölçeğinde tek kod yanıltıcı olur). */
            climateNoteTr: string | null;
            /** @description Hidrografya — kısa düzyazı not (nehir/göl/deniz anlatısı, TR). */
            hydrographyNoteTr: string | null;
            /** @description Egemenlik / uluslararası tanınma çerçevesi — serbest anlatı düzyazısı (TR). Yalnızca tanınma statüsü tartışmalı/standart-dışı ülkeler için doldurulur; sıradan ülkelerde null. */
            sovereigntyNoteTr: string | null;
            /**
             * Format: date-time
             * @description Kayıt oluşturulma zamanı.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Son güncelleme zamanı (SEO dateModified / sitemap lastmod).
             */
            updatedAt: string;
        };
        MarineValueDto: {
            /**
             * @description The value, or null when status !== ok. NOT suppressed when the sea is calm: a server-side null would become indistinguishable from a genuine no_data. The layer catalogue publishes calmThreshold instead, and the DISPLAY decides not to draw an arrow.
             * @example 23.5
             */
            value: number | null;
            /**
             * @description Canonical machine unit. Providers return three different strings for the same quantity (m / degree / degrees_C from CMEMS; m / ° / °C / km/h from Open-Meteo), so passthrough is not an option. Symbols are a display concern (web i18n).
             * @enum {string}
             */
            unit: "m" | "celsius" | "degree_true" | "meter_per_second";
            /**
             * @description Why the value is or is not present. not_supported is a PERMANENT product truth (CMEMS carries no wave field in the Marmara at all) and is distinct from no_data ("covered here, but nothing right now"); the two must not render alike.
             * @enum {string}
             */
            status: "ok" | "no_data" | "not_supported" | "unavailable";
            /**
             * @description Cache freshness, ALWAYS null when status !== ok. Deliberately separate from status: ok + stale is a normal, frequent combination (provider quiet for 20 minutes, we hold a 40-minute-old valid number).
             * @enum {string|null}
             */
            freshness: "fresh" | "stale" | null;
            /**
             * @description The MODEL time this value belongs to (ISO-8601 UTC). For CMEMS this is the time WE sent: the GetFeatureInfo reply carries no time field at all, yet the time parameter does change the value — so an explicit time is always sent and never defaulted. At runtime that instant is the hour nearest to the request moment, clamped into the dataset’s resolved temporal extent — so around a horizon edge it may sit up to a few hours behind "now", honestly labelled here and still bounded by the server’s validity-age ceiling.
             * @example 2026-07-30T12:00:00.000Z
             */
            validAtUtc: string | null;
            /**
             * @description When WE fetched it (ISO-8601 UTC, server clock).
             * @example 2026-07-30T12:04:11.000Z
             */
            fetchedAtUtc: string | null;
            /**
             * @description The model RUN this value came from (ISO-8601 UTC). ECMWF: the 00/06/12/18 UTC cycle, which the provider states in both the URL and the GRIB header. CMEMS: null — it publishes no run time per value. Added because it is the ONLY field that can reveal a stale forecast: an old cycle still produces a step valid "now", so validAtUtc looks current and fetchedAtUtc is genuinely recent while the numbers are two days old.
             * @example 2026-07-30T12:00:00.000Z
             */
            modelRunAtUtc: string | null;
            /** @description When this value first became stale (ISO-8601 UTC), or null while fresh. Two independent ceilings can retire a value: cache age and model validity age — they catch different failures, since a value fetched 10 minutes ago may belong to an 8-hour-old model step. */
            staleSinceUtc: string | null;
            /**
             * @description Which provider produced THIS field. Carried per field, never per response: mixing sources silently is banned (K6), and the Marmara wave fields legitimately come from a different provider than the temperature next to them.
             * @enum {string|null}
             */
            source: "cmems" | "ecmwf" | null;
            /**
             * @description Provider dataset identifier, verbatim, when the provider reports one. For CMEMS-sourced values the id is resolved from the provider STAC catalogue at runtime — never pinned in code — so the trailing version stamp (_2xxxxx) rotates with the provider and consumers must treat the string as opaque. Two values of the SAME field can therefore carry different ids across basins (and across a provider rotation) — never join on this string. ECMWF-sourced values carry null: that provider has no per-value dataset id, and modelRunAtUtc is the provenance there.
             * @example BLKSEA_ANALYSISFORECAST_PHY_007_001/cmems_mod_blk_phy-tem_anfc_mrm-500m_PT1H-i_202311
             */
            datasetId: string | null;
            /** @description Latitude of the model grid cell centre the value was read from. */
            gridLatitude: number | null;
            /** @description Longitude of the model grid cell centre the value was read from. */
            gridLongitude: number | null;
            /**
             * @description Distance from the requested coordinate to that grid centre, km. On BOTH Faz-1 sources this is an IN-CELL OFFSET, never a search distance: the value comes from the cell the coordinate falls in, and neither leg ever looks for a nearer wet cell. It therefore cannot exceed half a cell diagonal — ≤ ~2 km for the regional CMEMS grids, ≤ ~21 km for the 0.25° ECMWF grid (largest measured over the 30 reference points: 15.5 km) — and it cannot warn that data is far away. What it CAN do is expose a mapping bug: an offset above half a diagonal means the arithmetic picked the wrong cell.
             * @example 1.2
             */
            distanceKm: number | null;
        };
        MarineSeriesDto: {
            /**
             * @description Spacing between consecutive samples, hours. Uniform at 3 across the whole published horizon: ECMWF switches to 6-hourly steps only after +144 h, and the horizon stops at +120 h, so this stays a single honest number.
             * @example 3
             */
            stepHours: number;
            /**
             * @description Sample instants (ISO-8601 UTC). Defines the length of EVERY array below.
             * @example [
             *       "2026-07-30T00:00:00.000Z",
             *       "2026-07-30T03:00:00.000Z"
             *     ]
             */
            timesUtc: string[];
            /** @description Sea surface temperature, °C. Same length as timesUtc; nulls are gaps. ON THIS SERIES IT IS NULL FOR ITS WHOLE LENGTH: ECMWF Open Data publishes no sea-surface-temperature field in any of its streams (verified against the published parameter set of oper, wave, enfo and aifs-single). The array is kept rather than removed because the temperature series is a CMEMS concern and this shape must not change when M4 fills it. */
            seaSurfaceTemperature: (number | null)[];
            /** @description Significant wave height, m. Same length as timesUtc. */
            waveHeight: (number | null)[];
            /** @description Wave direction, degrees. True north, clockwise, 0–360. Per-field from/towards meaning is published in GET /api/marine/layers → directionConvention. This field is 'from'. */
            waveDirection: (number | null)[];
            /** @description Wind speed at 10 m, m/s (requested explicitly from the provider, never its default). */
            windSpeed10m: (number | null)[];
            /** @description Wind direction at 10 m, degrees. True north, clockwise, 0–360. Per-field from/towards meaning is published in GET /api/marine/layers → directionConvention. This field is 'from'. */
            windDirection10m: (number | null)[];
            /**
             * @description Always ecmwf — CMEMS answers one time step per call, so a 5-day series would cost ~120 requests per point.
             * @example ecmwf
             * @enum {string}
             */
            source: "ecmwf";
            /**
             * @description The model RUN this series came from (ISO-8601 UTC) — for ECMWF, the 00/06/12/18 UTC cycle; null for a provider that publishes none. Distinct from fetchedAtUtc and from validAtUtc, and it is the only one of the three that can expose a stale forecast: a two-day-old cycle still produces a step valid "now", so both of the other timestamps look fresh while the data is not.
             * @example 2026-07-30T12:00:00.000Z
             */
            modelRunAtUtc: string | null;
            /**
             * @description Last instant covered by this series (ISO-8601 UTC). NOT a constant: the published ECMWF horizon is +120 h from the model run, and while a cycle is still being ingested this is the last step actually held — it grows as the cycle completes. The web must read it rather than hardcode a slider bound.
             * @example 2026-08-04T00:00:00.000Z
             */
            horizonEndUtc: string;
        };
        MarinePointListItemDto: {
            /**
             * @description TR slug (routing key).
             * @example istanbul-marmara-aciklari
             */
            slugTr: string;
            /**
             * @description EN slug (routing key).
             * @example istanbul-marmara-offshore
             */
            slugEn: string;
            /**
             * @description Standalone full name, used where the point appears WITHOUT province context (the /deniz hub). İstanbul, Çanakkale and Balıkesir each have two points that show different numbers side by side, so the sea must be part of the name.
             * @example İstanbul – Marmara Açıkları
             */
            nameTr: string;
            /**
             * @description Standalone full name (EN).
             * @example İstanbul – Marmara Offshore
             */
            nameEn: string;
            /**
             * @description Province-relative short label, used INSIDE /turkiye/{il} where the province name is already in the heading and repeating it would be noise. GUARANTEE: derived from the point's seaBasin, and therefore UNIFORM across every point in a basin — the /deniz hub relies on it, taking the first point of a group as that basin's heading. Turning this into a per-point label would silently mislabel that heading, so it is a basin label that happens to be served per point, not a free-text field.
             * @example Marmara açıkları
             */
            coastLabelTr: string;
            /**
             * @description Province-relative short label (EN). Same per-basin uniformity guarantee.
             * @example Marmara offshore
             */
            coastLabelEn: string;
            /**
             * @description Plaka kodu of the province this point is published under (zero-padded).
             * @example 34
             */
            plateCode: string;
            /**
             * @description Requested latitude (decimal degrees). This is OUR chosen coordinate, not the model grid centre — the grid centre is per-provider and is served on the value payload as gridLatitude/gridLongitude.
             * @example 40.85
             */
            latitude: number;
            /**
             * @description Requested longitude (decimal degrees).
             * @example 28.8
             */
            longitude: number;
            /**
             * @description The POINT's basin, never the province's. İstanbul has one black_sea point and one marmara point; the basin also selects the CMEMS dataset, so deriving it from the province would query the wrong model.
             * @enum {string}
             */
            seaBasin: "aegean" | "mediterranean" | "marmara" | "black_sea";
            /**
             * @description Presentation order on the /deniz hub — a coastal traverse (Black Sea west→east, then Marmara, Aegean, Mediterranean), not alphabetical.
             * @example 2
             */
            displayOrder: number;
        };
        MarineOverviewPointDto: {
            /** @description The point this block describes. */
            point: components["schemas"]["MarinePointListItemDto"];
            /** @description Sea surface temperature (°C). */
            seaSurfaceTemperature: components["schemas"]["MarineValueDto"];
            /** @description Significant wave height (m) — the mean of the highest one third of waves. Individual waves can be noticeably higher; the /deniz hub is required to explain this in prose. */
            waveHeight: components["schemas"]["MarineValueDto"];
            /** @description Wave direction. True north, clockwise, 0–360. Per-field from/towards meaning is published in GET /api/marine/layers → directionConvention. This field is 'from'. */
            waveDirection: components["schemas"]["MarineValueDto"];
            /** @description Wind speed at 10 m (m/s). */
            windSpeed10m: components["schemas"]["MarineValueDto"];
            /** @description Wind direction at 10 m. True north, clockwise, 0–360. Per-field from/towards meaning is published in GET /api/marine/layers → directionConvention. This field is 'from'. */
            windDirection10m: components["schemas"]["MarineValueDto"];
        };
        MarineAttributionDto: {
            /**
             * @description Stable provider key, 'ecmwf' or 'cmems'. Joins to MarineLayerDto.attributionId, so a renderer can name the provider behind each layer.
             * @example cmems
             */
            providerId: string;
            /**
             * @description Provider display name, as the provider itself writes it in the mandated notice. Not a localizable label — do not translate it.
             * @example E.U. Copernicus Marine Service
             */
            providerName: string;
            /**
             * @description Licence name, verbatim. The legal name of a licence is never translated.
             * @example Copernicus Marine Service Commitments and Licence
             */
            licenceName: string;
            /**
             * @description Canonical licence URL. Use this exact URL — a localized Creative Commons variant is not the same document.
             * @example https://marine.copernicus.eu/user-corner/service-commitments-and-licence
             */
            licenceUrl: string;
            /** @description The notice the licence REQUIRES us to display, VERBATIM and IN ENGLISH. Not editorial copy: shortening, restyling, reordering or translating it is a licence breach, so it is data, not a template. Render it as-is and mark it lang="en" even on the Turkish locale. For ECMWF it starts with a copyright line whose year comes from the data behind this very response; when no ECMWF cycle has been ingested that line is OMITTED rather than faked, and the notice begins at the mandatory service sentence. */
            requiredNoticeEn: string;
            /** @description The liability disclaimer the licence requires, VERBATIM and IN ENGLISH, or null where the licence imposes none. Separate from requiredNoticeEn because the two providers genuinely differ: ECMWF mandates a disclaimer, the Copernicus Marine licence does not. Merging them into one string would tell the reader CMEMS carries a disclaimer it does not. Render it next to the notice, same lang="en" rule. */
            disclaimerEn: string | null;
            /** @description Informational Turkish rendering of this row as a whole — the notice, plus the disclaimer where the licence imposes one (so the ECMWF row covers requiredNoticeEn AND disclaimerEn in a single paragraph, while the CMEMS row has no disclaimer to render). It stands ALONGSIDE requiredNoticeEn and MUST NEVER REPLACE IT — not even on the Turkish locale. ECMWF's terms say the wording "shall be attached" and, unlike the Copernicus framework, offer no "or any similar notice" escape, so the English text is the one that discharges the obligation. This field exists so a Turkish reader can understand it, not so a renderer can substitute it. Renamed from requiredNoticeTr in M5 precisely because the old name implied the opposite. */
            explanationTr: string;
            /** @description Deliberately null — DOIs live in data-provenance.md (DEC 2026-08-02g §2), not on the page. Serving one here would hand the web the easiest possible way to break that rule, and a single DOI cannot represent the five CMEMS products behind these values anyway: picking one would be a false statement about provenance. */
            doi: string | null;
            /** @description Deliberately null — same reasoning as doi. Neither licence requires a product title in the visible notice, and the marine values are merged across several products per field. */
            productTitle: string | null;
        };
        MarineOverviewDto: {
            points: components["schemas"]["MarineOverviewPointDto"][];
            /**
             * @description When the freshest contributing value entered the server cache (ISO-8601 UTC) — deliberately DATA-derived rather than the wall clock, so the body stays byte-identical between requests that serve the same cached data and the weak ETag / 304 revalidation works. Falls back to the wall clock only on the dataAvailable=false response, which is no-store and never cached.
             * @example 2026-07-30T12:04:11.000Z
             */
            generatedAtUtc: string;
            /**
             * @description False only in the narrow window where the cache is genuinely empty (first boot before the first warmup tick, or after a cache flush). The response is still 200 — a 5xx would break the web build, which is the one thing these endpoints must never do — but it carries Cache-Control: no-store and this flag. CONTRACT: a response with dataAvailable=false MUST NOT be committed by ISR/SSG; keep the previous render. That is what stops an empty /deniz page from being indexed.
             * @example true
             */
            dataAvailable: boolean;
            attributions: components["schemas"]["MarineAttributionDto"][];
        };
        MarineConditionsDto: {
            /** @description The point this block describes. */
            point: components["schemas"]["MarinePointListItemDto"];
            /** @description Sea surface temperature (°C). */
            seaSurfaceTemperature: components["schemas"]["MarineValueDto"];
            /** @description Significant wave height (m). */
            waveHeight: components["schemas"]["MarineValueDto"];
            /** @description Wave direction. True north, clockwise, 0–360. Per-field from/towards meaning is published in GET /api/marine/layers → directionConvention. This field is 'from'. */
            waveDirection: components["schemas"]["MarineValueDto"];
            /** @description Wind speed at 10 m (m/s). */
            windSpeed10m: components["schemas"]["MarineValueDto"];
            /** @description Wind direction at 10 m. True north, clockwise, 0–360. Per-field from/towards meaning is published in GET /api/marine/layers → directionConvention. This field is 'from'. */
            windDirection10m: components["schemas"]["MarineValueDto"];
            /** @description The 5-day series, or null. Nullable for a real case, not for convenience: CMEMS may be up while Open-Meteo is down, which yields instant values with no series. */
            series: components["schemas"]["MarineSeriesDto"] | null;
            /**
             * @description SERVER-COMPUTED. True when the chart comes from a different model than the headline instant value, which measurably happens (~1.5–1.7 °C apart at the same point). When true the web MUST render the fixed i18n notice marine.series.sourceDiffersNotice. It is a boolean rather than a design-guide sentence precisely so it can be asserted in a contract test instead of quietly skipped.
             * @example true
             */
            seriesSourceDiffersFromInstant: boolean;
        };
        MarineProvinceConditionsDto: {
            /**
             * @description Plaka kodu (zero-padded).
             * @example 34
             */
            plateCode: string;
            /** @description One entry per marine point of this province, in displayOrder. Two entries for the three two-sea provinces; they legitimately disagree and must be labelled by sea. */
            marinePoints: components["schemas"]["MarineConditionsDto"][];
            attributions: components["schemas"]["MarineAttributionDto"][];
        };
        MarineColorStopDto: {
            /**
             * @description Value the stop is anchored at, in the layer unit.
             * @example 20
             */
            value: number;
            /**
             * @description Colour, `#rrggbb`.
             * @example #2c7fb8
             */
            hex: string;
        };
        MarineLayerDto: {
            /**
             * @description Layer id, snake_case. It corresponds one-to-one with a MarineValueDto property on the conditions/overview payloads, but those are camelCase — sea_surface_temperature ↔ seaSurfaceTemperature — so convert the case rather than indexing the payload by this id.
             * @enum {string}
             */
            id: "sea_surface_temperature" | "wave_height" | "wave_direction" | "wind_speed_10m" | "wind_direction_10m";
            /**
             * @description Display label (TR).
             * @example Deniz suyu sıcaklığı
             */
            labelTr: string;
            /**
             * @description Display label (EN).
             * @example Sea surface temperature
             */
            labelEn: string;
            /**
             * @description Canonical unit of this layer’s values.
             * @enum {string}
             */
            unit: "m" | "celsius" | "degree_true" | "meter_per_second";
            /**
             * @description What a degree MEANS for this layer; null for non-direction layers. True north, clockwise, 0–360. Per-field from/towards meaning is published in GET /api/marine/layers → directionConvention. ARROW-UNLOCK CONDITION (binding, and now MET for wind_speed_10m and wind_direction_10m): a direction arrow may be drawn once this field is published AND the three-layer wind regression suite is green — (1) a table of eight cardinal vectors mapped to expected bearings, (2) the invariants every bearing in [0, 360), speed >= 0, speed >= |u| and |v|, and a null component producing a null bearing rather than 0, and (3) a committed real ECMWF GRIB message decoded and compared against ecCodes reference values. All three ship in src/marine/ecmwf/ and run on CI. The condition exists because ECMWF publishes wind as the vector components 10u/10v, so the bearing is SERVER-DERIVED arithmetic: a sign error produces a bearing exactly 180 degrees wrong, and a reversed arrow is indistinguishable from a correct one on screen. Wave direction is not derived — ECMWF states mwd as "degree true, zero means coming from the north" and it is published verbatim.
             * @enum {string|null}
             */
            directionConvention: "from" | "towards" | null;
            /**
             * @description Below this magnitude the sea/wind counts as CALM. Published on the MAGNITUDE layer (wave_height, wind_speed_10m) and it governs the PAIRED direction layer: when wave_height < its calmThreshold the web shows a calm indicator instead of a wave_direction arrow, and likewise for wind. Null on the direction layers themselves and on temperature. The server never suppresses the direction value — nulling it would make "calm" indistinguishable from "no data".
             * @example 0.1
             */
            calmThreshold: number | null;
            /**
             * @description Primary provider for this layer.
             * @enum {string}
             */
            primarySource: "cmems" | "ecmwf";
            /**
             * @description Provider used where the primary does not cover the point (CMEMS carries no wave field in the Marmara), or null when there is no fallback.
             * @enum {string|null}
             */
            fallbackSource: "cmems" | "ecmwf" | null;
            /**
             * @description Series step for this layer, hours.
             * @example 3
             */
            stepHours: number;
            /** @description Last instant the PRIMARY provider can serve (ISO-8601 UTC), or null while the provider catalogue is unresolved. ECMWF layers: the newest ingested cycle’s published horizon. CMEMS layers: the MINIMUM of the serving products’ temporal-extent ends — the layer is one field for every basin, so the only horizon it can honour everywhere is the earliest one; it nulls when any serving product is unresolved or open-ended. The horizon is genuinely variable (4–9 days by product), so the web must read it here rather than hardcode a slider bound. */
            horizonEndUtc: string | null;
            /**
             * @description How often the provider re-runs the model, as the provider states it — PROVIDER-VERBATIM and not machine-parseable by contract. For CMEMS layers this is the STAC updateFrequencies compaction; when the serving products state different cadences the distinct strings are joined with " | ". Null while the catalogue is unresolved. Carried at LAYER level rather than per value because neither Faz-1 provider publishes a model-run time per value.
             * @example daily: 16:00; 20th of each month at 16UTC
             */
            updateFrequency: string | null;
            /** @description When the provider last updated its catalogue entry (ISO-8601 UTC), or null while unresolved. ECMWF layers: the model-run time of the newest ingested cycle (that provider has no catalogue document to date-stamp). CMEMS layers: the NEWEST admp_updated stamp across the serving products. */
            catalogueUpdatedAtUtc: string | null;
            /** @description Colour ramp for this layer, ascending by value. */
            colorStops: components["schemas"]["MarineColorStopDto"][];
            /**
             * @description Key of the MarineAttributionDto that must accompany this layer. The rows themselves are a compiled catalogue (src/marine/marine-attribution-catalogue.ts), NOT a seeded table and NOT a resolving endpoint: they are served inline as attributions[] on the value responses (GET /api/marine/overview and GET /api/marine/provinces/{plateCode}/conditions). Join on this key to name the provider behind a layer.
             * @example cmems
             */
            attributionId: string;
        };
        AirQualityPollutantValueDto: {
            /**
             * @example pm2_5
             * @enum {string}
             */
            pollutant: "pm2_5" | "pm10" | "no2" | "o3" | "so2";
            /**
             * @description Raw model concentration in µg/m³, or null when this step/pollutant is missing. Model output on a ~0.1° grid — never a station reading. Missing values are null, never a sentinel: the provider marks absence with an in-band fill value that the server classifies away before publication.
             * @example 8.4
             */
            value: number | null;
            /**
             * @description Canonical machine unit token. The display symbol (µg/m³) is a web i18n concern.
             * @enum {string}
             */
            unit: "ug_m3";
            /**
             * @description EAQI-2024 rates ALL five pollutants on hourly values (no 24 h running mean), so this enum has a single member. A future methodology change arrives as a new indexSystem member, not a silent reinterpretation of this field.
             * @enum {string}
             */
            averagingPeriod: "hourly";
            /**
             * @description EAQI sub-index band for this pollutant alone; null when value is null.
             * @example 2
             */
            subIndexBand: number | null;
            /**
             * @example fair
             * @enum {string|null}
             */
            subIndexCategory: "good" | "fair" | "moderate" | "poor" | "very_poor" | "extremely_poor" | null;
            /**
             * @description Per-pollutant status: the same cell can carry PM2.5 and miss SO₂ — pollutants are classified independently, never averaged or borrowed from a neighbour cell.
             * @enum {string}
             */
            status: "ok" | "no_data" | "not_supported" | "unavailable";
        };
        AirQualityIndexDto: {
            /**
             * @description Overall EAQI band = the WORST per-pollutant sub-band. Null unless status=ok.
             * @example 2
             */
            band: number | null;
            /**
             * @description Category TOKEN for the band — never user-facing text; TR/EN names and the "our translation" label are web i18n keys.
             * @enum {string|null}
             */
            category: "good" | "fair" | "moderate" | "poor" | "very_poor" | "extremely_poor" | null;
            /**
             * @description The pollutant that set the worst band. Ties are broken deterministically by the published order (see GET /api/air-quality/index-system → tieBreakOrder).
             * @enum {string|null}
             */
            dominantPollutant: "pm2_5" | "pm10" | "no2" | "o3" | "so2" | null;
            /**
             * @description Which index methodology produced band/category. The full band table behind this token is published at GET /api/air-quality/index-system; the web must not hardcode it. Adding a member is treated as a BREAKING change (exhaustive switches).
             * @enum {string}
             */
            indexSystem: "eaqi-eea-2024";
            /** @enum {string} */
            status: "ok" | "no_data" | "not_supported" | "unavailable";
            /**
             * @description Cache freshness; ALWAYS null when status !== ok.
             * @enum {string|null}
             */
            freshness: "fresh" | "stale" | null;
            /** @description Raw per-pollutant concentrations + sub-indexes (DEC 2026-07-30w: the index stays auditable against the numbers it came from). */
            pollutants: components["schemas"]["AirQualityPollutantValueDto"][];
            /** @description Pollutants missing at this instant. A partial index is still published; honesty here means SAYING what is missing, not hiding what is known. All five missing → status no_data. */
            missingPollutants: ("pm2_5" | "pm10" | "no2" | "o3" | "so2")[];
            /**
             * @description The model step this value belongs to (ISO-8601 UTC). Derived from the REQUESTED run day + hour offset — the file’s own free-text time label is only cross-validated, never parsed as the source of truth.
             * @example 2026-08-01T14:00:00.000Z
             */
            validAtUtc: string | null;
            /**
             * @description CAMS model run base time (00:00 UTC of the run day) — the "model time".
             * @example 2026-08-01T00:00:00.000Z
             */
            modelRunAtUtc: string | null;
            /**
             * @description When the run file was downloaded and decoded by this server.
             * @example 2026-08-01T12:41:03.000Z
             */
            ingestedAtUtc: string | null;
            /**
             * @description When THIS response was compiled from the local store (cache semantics only — the model/ingest instants above are the honest data times).
             * @example 2026-08-01T14:03:11.000Z
             */
            fetchedAtUtc: string | null;
            /**
             * @description When the served value started counting as stale; null while fresh.
             * @example null
             */
            staleSinceUtc: string | null;
            /** @enum {string} */
            source: "cams-europe-aq";
            /**
             * @description Provider dataset identifier, verbatim.
             * @example cams-europe-air-quality-forecasts
             */
            datasetId: string | null;
            /**
             * @description Latitude of the grid-cell CENTRE the value was read from.
             * @example 39.95
             */
            gridLatitude: number | null;
            /** @example 32.85 */
            gridLongitude: number | null;
            /**
             * @description Distance (km) between the requested province reference point and the grid-cell centre. This is the WITHIN-CELL offset of nearest-cell sampling — never the result of searching for a "better" cell; interpolation and averaging are banned by design.
             * @example 3.1
             */
            distanceKm: number | null;
            /**
             * @description Model grid resolution in degrees (~11 km background level). Street-level differences are below this resolution by construction — honest-presentation field.
             * @example 0.1
             */
            gridResolutionDegrees: number;
        };
        AirQualitySeriesConcentrationsDto: {
            /** @description µg/m³ per step; null per missing step. */
            pm2_5: (number | null)[];
            pm10: (number | null)[];
            no2: (number | null)[];
            o3: (number | null)[];
            so2: (number | null)[];
        };
        AirQualitySeriesDto: {
            /**
             * @description Step instants (ISO-8601 UTC). INVARIANT: every other array in this object has exactly this length; a missing step is null in place, never dropped and never invented. Consecutive steps are exactly one hour apart. Steps BEFORE analysisEndUtc come from the provider ANALYSIS product; that instant and everything after it come from the FORECAST product. Both are model output, neither is an observation. When analysisEndUtc is null the series starts at the model run base time and contains no earlier step.
             * @example [
             *       "2026-08-01T00:00:00.000Z",
             *       "2026-08-01T01:00:00.000Z"
             *     ]
             */
            timesUtc: string[];
            /**
             * @description The instant the ANALYSIS half ends and the FORECAST half begins — always the model run base time. Steps before this instant come from the provider’s ANALYSIS product; this instant and everything after it come from the FORECAST product. Both are model output, not observations. Null when this run carries no analysis product at all, in which case the whole series is forecast.
             * @example 2026-08-01T00:00:00.000Z
             */
            analysisEndUtc: string | null;
            /**
             * @description Hours between steps (always 1 in Faz-1).
             * @example 1
             */
            stepHours: number;
            /**
             * @description End of the published horizon — the last entry of timesUtc (run base + 96 h in Faz-1).
             * @example 2026-08-05T00:00:00.000Z
             */
            horizonEndUtc: string;
            /** @description Overall EAQI band per step; null where it cannot be computed. */
            bands: (number | null)[];
            categories: ("good" | "fair" | "moderate" | "poor" | "very_poor" | "extremely_poor" | null)[];
            dominantPollutants: ("pm2_5" | "pm10" | "no2" | "o3" | "so2" | null)[];
            concentrations: components["schemas"]["AirQualitySeriesConcentrationsDto"];
        };
        AirQualityAttributionDto: {
            /** @example Copernicus Atmosphere Monitoring Service (CAMS) */
            providerName: string;
            /** @example CAMS European air quality forecasts */
            productName: string;
            /** @example https://ads.atmosphere.copernicus.eu/datasets/cams-europe-air-quality-forecasts */
            datasetUrl: string;
            /**
             * @description The licence the dataset actually requires (measured: cc-by, revision 1).
             * @example Creative Commons Attribution 4.0 International (CC-BY-4.0)
             */
            licenceName: string;
            /** @example https://creativecommons.org/licenses/by/4.0/ */
            licenceUrl: string;
            /**
             * @description Verbatim required attribution line — never translated. The year is the run’s.
             * @example Contains modified Copernicus Atmosphere Monitoring Service information 2026
             */
            attributionText: string;
            /**
             * @description Verbatim required disclaimer — never translated.
             * @example Neither the European Commission nor ECMWF is responsible for any use that may be made of the Copernicus information or data it contains.
             */
            disclaimerText: string;
            /**
             * @description i18n keys for the editorial notices (model nature, grid resolution, category-name translation). The API ships KEYS only; the texts are authored on the web side. Adding a key is additive; removing or renaming one is a breaking contract change.
             * @example [
             *       "airQuality.notice.modelOutput",
             *       "airQuality.notice.gridResolution",
             *       "airQuality.notice.categoryTranslation"
             *     ]
             */
            noticeKeys: string[];
        };
        AirQualityProvinceDto: {
            /**
             * @description Zero-padded plate code.
             * @example 06
             */
            plateCode: string;
            /** @example ankara */
            slugTr: string;
            /** @example ankara */
            slugEn: string;
            /** @example Ankara */
            nameTr: string;
            /**
             * @description The canonical province reference point the platform uses everywhere.
             * @example 39.9727
             */
            latitude: number;
            /** @example 32.8637 */
            longitude: number;
            /** @description The value for the step nearest to now. */
            current: components["schemas"]["AirQualityIndexDto"];
            series: components["schemas"]["AirQualitySeriesDto"] | null;
            attribution: components["schemas"]["AirQualityAttributionDto"];
            /** @description False on the cold path (no usable run) — the page renders, the widget degrades. */
            dataAvailable: boolean;
        };
        AirQualityProvinceListItemDto: {
            /** @example 06 */
            plateCode: string;
            /** @example ankara */
            slugTr: string;
            /** @example ankara */
            slugEn: string;
            /** @example 2 */
            band: number | null;
            /** @enum {string|null} */
            category: "good" | "fair" | "moderate" | "poor" | "very_poor" | "extremely_poor" | null;
            /** @enum {string|null} */
            dominantPollutant: "pm2_5" | "pm10" | "no2" | "o3" | "so2" | null;
            /** @enum {string} */
            status: "ok" | "no_data" | "not_supported" | "unavailable";
            /** @example 2026-08-01T14:00:00.000Z */
            validAtUtc: string | null;
        };
        AirQualityIndexSystemCategoryDto: {
            /** @example 2 */
            band: number;
            /**
             * @example fair
             * @enum {string}
             */
            category: "good" | "fair" | "moderate" | "poor" | "very_poor" | "extremely_poor";
        };
        AirQualityIndexSystemPollutantDto: {
            /** @enum {string} */
            pollutant: "pm2_5" | "pm10" | "no2" | "o3" | "so2";
            /** @enum {string} */
            averagingPeriod: "hourly";
            /**
             * @description Upper bounds (µg/m³) of bands 1..5; band 6 is unbounded above the last value. Interpreted under boundaryRule — the upper bound belongs to ITS band.
             * @example [
             *       5,
             *       15,
             *       50,
             *       90,
             *       140
             *     ]
             */
            upperBoundsUgM3: number[];
        };
        AirQualityIndexSystemDto: {
            /** @enum {string} */
            indexSystem: "eaqi-eea-2024";
            /**
             * @description Band boundary rule, machine-readable: (lo, hi] — a value equal to an upper bound falls in THAT band (PM2.5 = 15.0 µg/m³ → band 2). The last band has no upper bound.
             * @example lower_exclusive_upper_inclusive
             * @enum {string}
             */
            boundaryRule: "lower_exclusive_upper_inclusive";
            categories: components["schemas"]["AirQualityIndexSystemCategoryDto"][];
            pollutants: components["schemas"]["AirQualityIndexSystemPollutantDto"][];
            /** @description Deterministic dominant-pollutant tie-break order when two pollutants share the worst band. */
            tieBreakOrder: ("pm2_5" | "pm10" | "no2" | "o3" | "so2")[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    ProvinceController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvinceListItemDto"][];
                };
            };
        };
    };
    ProvinceController_findMapSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvinceMapSummaryDto"][];
                };
            };
        };
    };
    ProvinceController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TR or EN slug of the province. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvinceDetailDto"];
                };
            };
            /** @description No province matches the given slug. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CountryController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryListItemDto"][];
                };
            };
        };
    };
    CountryController_findMapSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryMapSummaryDto"][];
                };
            };
        };
    };
    CountryController_findBySlug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TR or EN slug of the country. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryDetailDto"];
                };
            };
            /** @description No country matches the given slug. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MarineController_findAllPoints: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarinePointListItemDto"][];
                };
            };
        };
    };
    MarineController_findAllLayers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarineLayerDto"][];
                };
            };
        };
    };
    MarineController_getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarineOverviewDto"];
                };
            };
            /** @description The marine feature is not enabled on this deployment. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MarineController_getConditions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description TR or EN slug. */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarineConditionsDto"];
                };
            };
            /** @description The slug is not a well-formed kebab-case identifier. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No marine point matches the slug, or the marine feature is disabled. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MarineController_getProvinceConditions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plaka kodu, zero-padded. */
                plateCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarineProvinceConditionsDto"];
                };
            };
            /** @description plateCode is not exactly two digits. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The province has no marine reference point (inland), or the marine feature is disabled. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AirQualityController_getIndexSystem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirQualityIndexSystemDto"];
                };
            };
        };
    };
    AirQualityController_listProvinces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirQualityProvinceListItemDto"][];
                };
            };
        };
    };
    AirQualityController_getProvince: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Two-digit zero-padded province plate code. */
                plateCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AirQualityProvinceDto"];
                };
            };
            /** @description plateCode is not exactly two digits. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No province carries this plate code. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
