"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useTranslations } from "next-intl";
import { consumeResolved, requestAuth, useAuthModalState } from "@/lib/auth/auth-modal.client";
import { useAuthSession } from "@/lib/auth/use-session.client";
import { submitGameRound } from "@/lib/game-rounds/client";
import type { RoundSummary } from "@/lib/game/round";
import { LockIcon } from "./game-icons";
import styles from "./game-round-save.module.css";

/**
 * The login-gated "save this round" control (UYELIK-10 plan §5.6) — a new section inside
 * `GameSummary`'s `dialogBody`, after the review/missed groups and before the closing
 * `dialogActions` row: a "save my result" action is semantically distinct from "Tekrar
 * oyna / Mod seçimine dön / Kapat", so it is not merged into that button row.
 *
 * Owns `useAuthSession()` itself — decoupled, the way `FavoriteButton` owns its own auth
 * check rather than receiving it as a prop; `GameSummary` passes only pure round data.
 *
 * A ONE-SHOT COMMIT, not a toggle, unlike `FavoriteButton`'s `role="switch"` shape (§2.4):
 * there is no "unsave". Once `submitGameRound` reports success the control settles into a
 * permanent `saved` state for the lifetime of this mounted round (a genuine replay
 * unmounts/remounts this component with a fresh `clientRoundId`, resetting it correctly).
 *
 * THE IDEMPOTENCY GUARANTEE THIS CONTROL RELIES ON, NOT REIMPLEMENTS: `clientRoundId` is
 * generated once at `createRound` (`lib/game/round.ts`) and never regenerated by any
 * transition — a resumed submit (uyelik-auth-redesign plan §5.6.2) or a retried one (network
 * retry, a double-click that slips past the pending guard) resubmits the SAME id, which the
 * api deduplicates server-side (plan §2.2/§10 item 1). This control's own job is only to not
 * spend a second call while one is already in flight or already settled.
 *
 * RESUME (uyelik-auth-redesign plan §5.6.2, superseding an earlier full-page `/kayit`
 * redirect) — this is the §2.4 case the redesign plan measured as genuinely IMPOSSIBLE
 * before: a page redirect destroyed the finished round with no way back. The auth modal
 * changes nothing in the DOM, so the resume simply calls the same `submit` function the
 * authenticated click path calls. `authRequestId` is a plain `useRef` (never triggers a
 * render on its own); `consumeResolved` returning `true` exactly once makes a double-submit
 * impossible even under React 19 Strict Mode's double-invoked effects (K3) — on top of the
 * idempotency guarantee above, which would in any case deduplicate it server-side.
 *
 * Nested-`<dialog>` note (K4): this control renders inside `GameSummary`'s own open
 * `<dialog>`. The auth dialog's `showModal()` stacks above it in the browser's top layer and
 * renders it inert; on close, focus returns to this control inside the still-open summary
 * dialog (verified empirically, §11.4.2).
 */
export function GameRoundSaveControl({
  summary,
  clientRoundId,
  submitModeTag,
}: {
  readonly summary: RoundSummary;
  readonly clientRoundId: string;
  readonly submitModeTag: string;
}) {
  const t = useTranslations("GameRounds");
  const [authState] = useAuthSession();
  const modal = useAuthModalState();
  const [status, setStatus] = useState<"idle" | "pending" | "saved" | "failed">("idle");
  const authRequestId = useRef<string | null>(null);

  /** The interrupted action itself — shared by the authenticated click path and the resume
   *  effect below. Reads `summary`/`clientRoundId`/`submitModeTag` fresh on every call, never
   *  a stale ref-captured snapshot. */
  const submit = useCallback(async () => {
    setStatus("pending");
    const result = await submitGameRound({
      mode: submitModeTag,
      clientRoundId,
      score: summary.score,
      found: summary.found,
      firstTry: summary.firstTry,
      total: summary.total,
      poolTotal: summary.poolTotal,
      totalWrongs: summary.totalWrongs,
      endedEarly: summary.endedEarly,
      // completionTimeSeconds omitted — this engine tracks no clock (DEC 2026-07-30m/30n);
      // the api's own contract already accommodates this exactly (plan §5.6).
    });
    setStatus(result.ok ? "saved" : "failed");
  }, [clientRoundId, submitModeTag, summary]);

  async function handleClick() {
    // The pending/settled guard is the FIRST statement — the same
    // `if (pending) return;` position `FavoriteButton`'s `handleClick` and
    // `VideoProgressControls`'s `handleToggle` both take, because `aria-disabled` alone
    // does not stop the browser from firing a second click/Enter/Space.
    if (authState === "checking" || status === "pending" || status === "saved") return;
    if (authState === "anonymous") {
      authRequestId.current = requestAuth("gameRound");
      return;
    }
    await submit();
  }

  // The resume: signed out → modal → login/register → the round that was impossible to save
  // before this redesign now completes, with the summary dialog never closing underneath it.
  useEffect(() => {
    const id = authRequestId.current;
    if (id === null || modal.resolvedRequestId !== id) return;
    if (!consumeResolved(id)) return;
    authRequestId.current = null;
    void submit();
  }, [modal.resolvedRequestId, submit]);

  const pending = status === "pending";
  const saved = status === "saved";

  return (
    <div className={styles.wrapper}>
      {authState === "checking" ? (
        // Renders in the SAME interactive shape the authenticated/not-yet-saved branch
        // below does — never the lock-icon shape, which would assert "sign-in required"
        // before the real state is even known — just non-actionable while it resolves, and
        // reserving the same box so nothing shifts a moment later.
        <button type="button" className="btn btn-primary" aria-disabled={true}>
          {t("saveLabel")}
        </button>
      ) : authState === "anonymous" ? (
        <button
          type="button"
          className="btn btn-ghost"
          aria-label={t("signInRequiredAria")}
          onClick={() => void handleClick()}
        >
          {/* Decorative — the accessible name above already states the fact in full, the
              same posture `FavoriteButton`'s own guest-branch lock glyph takes. */}
          <LockIcon size={14} />
          {t("saveLabel")}
        </button>
      ) : saved ? (
        // A11Y96-I1 fix (PR #96 round-1 review): a genuine, permanent outcome — but NEVER a
        // real `disabled` attribute here, even though there is no future click this control
        // still needs to stay actionable for. This is the SAME DOM node the reader just
        // clicked and is still focused; a real `disabled` yanks focus silently with no AT
        // announcement (WCAG 4.1.3). `aria-disabled` in every non-interactive state — the
        // same posture `favorite-button.tsx` holds throughout its own lifecycle, never
        // switching to real `disabled` for any of its states. The label-text change itself is
        // announced by the sr-only `role="status"` paragraph below, mirroring the mechanism
        // the `failed` branch already uses for its own error text.
        <button type="button" className="btn btn-primary" aria-disabled={true}>
          {t("savedLabel")}
        </button>
      ) : (
        <button
          type="button"
          className="btn btn-primary"
          aria-disabled={pending}
          onClick={() => void handleClick()}
        >
          {t("saveLabel")}
        </button>
      )}
      {saved && (
        // A11Y96-I1 fix: the visible signal for "Kaydet" → "Kaydedildi" is the button's own
        // label text (sighted users), but that text swap alone reaches no screen reader —
        // the changed text lives inside the SAME node, which most AT does not re-announce on
        // a plain content change. This sr-only `role="status"` paragraph is the announcement
        // channel, mirroring exactly the mechanism `status === "failed"` already uses below
        // for its own (visible) error text — reusing `savedLabel` rather than a new string,
        // since the fact being announced is the same one the button already shows.
        <p role="status" className={styles.srOnly}>
          {t("savedLabel")}
        </p>
      )}
      {status === "failed" && (
        <p role="status" className={styles.error}>
          {t("saveError")}
        </p>
      )}
    </div>
  );
}
